name: nova_board
description: "NovaBoard - A project management application based on Trello."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/LogoApp.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/LogoApp.png
    - lib/assets/LogoSombre.png
    - lib/assets/LogoTrello.png
    - lib/assets/FondApp.png